import Link from "next/link";
import { ArrowDownRight, ArrowRight, Check, CircleDotDashed, Clock3, Compass, Layers3, MoveUpRight, Target } from "lucide-react";

export default function Home() {
  return (
    <main className="atlas-page min-h-screen overflow-hidden bg-[#eff2eb] text-[#10261b]">
      <section className="atlas-hero relative min-h-screen bg-[#103626] px-5 pb-14 pt-5 text-[#f6f8f1] sm:px-8 lg:px-12">
        <nav className="relative z-20 mx-auto flex max-w-7xl items-center justify-between rounded-full border border-white/15 bg-white/[.06] px-4 py-3 backdrop-blur-xl sm:px-5">
          <Link href="/" className="font-display text-xl font-black tracking-[-.06em]">nGamp<span className="text-[#c8ef70]">US</span></Link>
          <div className="flex items-center gap-1.5 text-sm font-bold"><Link href="/login" className="hidden rounded-full px-4 py-2 text-[#c9dbce] hover:bg-white/10 hover:text-white sm:block">Masuk</Link><Link href="/register" className="rounded-full bg-[#c8ef70] px-4 py-2.5 text-[#103626] shadow-[0_7px_0_#83a936] hover:-translate-y-0.5">Buat ruangmu</Link></div>
        </nav>

        <div className="atlas-grain absolute inset-0 opacity-30"/>
        <div className="atlas-sun absolute -right-32 top-20 h-96 w-96 rounded-full"/>

        <div className="relative z-10 mx-auto grid max-w-7xl gap-12 pb-8 pt-20 lg:grid-cols-[1.03fr_.97fr] lg:items-center lg:pt-28">
          <div className="max-w-3xl">
            <div className="inline-flex items-center gap-2 rounded-full border border-[#c8ef70]/30 bg-[#c8ef70]/10 px-3 py-1.5 text-[11px] font-black tracking-[.16em] text-[#d8f89a]"><CircleDotDashed size={14}/> CAMPUS ATLAS / 01</div>
            <h1 className="font-display mt-7 text-5xl font-black leading-[.9] tracking-[-.075em] sm:text-6xl lg:text-[5.8rem]">Kuliah jalan.<br/><span className="atlas-accent">Ambis tetap</span><br/>terarah.</h1>
            <p className="mt-7 max-w-xl text-lg leading-8 text-[#c8d8ce]">Satu ruang yang memetakan tugas, peran, dan deadline—supaya hidup kampusmu tidak lagi terasa seperti puluhan tab yang saling mengejar.</p>
            <div className="mt-9 flex flex-wrap items-center gap-4"><Link href="/register" className="inline-flex items-center gap-3 rounded-2xl bg-[#f6f8f1] px-5 py-4 font-extrabold text-[#103626] shadow-xl shadow-black/15 hover:-translate-y-1">Mulai petakan semester <ArrowRight size={18}/></Link><a href="#atlas" className="inline-flex items-center gap-2 font-bold text-[#d8f89a] hover:text-white">Lihat cara kerja <ArrowDownRight size={17}/></a></div>
            <div className="mt-12 flex flex-wrap gap-x-8 gap-y-3 border-t border-white/15 pt-5 text-sm text-[#b9ccc0]"><span><b className="text-[#f6f8f1]">01 dashboard</b> untuk semua fokus</span><span><b className="text-[#f6f8f1]">0 tab</b> yang terlupakan</span></div>
          </div>

          <div className="relative mx-auto w-full max-w-[540px] pb-8 pt-4 lg:pt-0">
            <div className="atlas-arc absolute -left-20 -top-16 h-[420px] w-[420px] rounded-full"/>
            <div className="atlas-board relative rotate-[2deg] rounded-[2rem] border border-white/15 bg-[#f6f8f1] p-3 text-[#10261b] shadow-2xl shadow-black/30 sm:p-4">
              <div className="rounded-[1.55rem] bg-[#e8eee7] p-4 sm:p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black tracking-[.16em] text-[#6d7b70]">FRIDAY / WEEK 05</p><h2 className="font-display mt-1 text-2xl font-black tracking-[-.05em]">Your focus map.</h2></div><span className="grid h-10 w-10 place-items-center rounded-full bg-[#103626] text-[#c8ef70]"><Compass size={19}/></span></div>
                <div className="mt-5 grid gap-3 sm:grid-cols-[1.15fr_.85fr]"><div className="rounded-2xl bg-[#103626] p-4 text-white"><div className="flex items-center justify-between text-xs font-bold text-[#c1d4c7]"><span>PRIORITAS UTAMA</span><span className="rounded-full bg-[#d9684e] px-2 py-1 text-[10px] text-white">BESOK</span></div><p className="font-display mt-5 text-xl font-black leading-tight">Finalisasi proposal Pengmas</p><div className="mt-6 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full w-[78%] rounded-full bg-[#c8ef70]"/></div><p className="mt-2 text-xs text-[#bdd0c2]">78% siap dikumpulkan</p></div><div className="rounded-2xl border border-[#c9d9cc] bg-white p-4"><p className="text-[10px] font-black tracking-[.14em] text-[#6d7b70]">MINGGU INI</p><p className="font-display mt-2 text-4xl font-black text-[#103626]">04<span className="text-lg text-[#77857b]">/07</span></p><p className="mt-1 text-xs font-semibold text-[#68766d]">komitmen selesai</p><div className="mt-4 flex -space-x-2"><span className="grid h-7 w-7 place-items-center rounded-full border-2 border-white bg-[#e7d4ff] text-[10px] font-black text-[#69469a]">K</span><span className="grid h-7 w-7 place-items-center rounded-full border-2 border-white bg-[#dff3e5] text-[10px] font-black text-[#0f6849]">O</span><span className="grid h-7 w-7 place-items-center rounded-full border-2 border-white bg-[#ffe9bf] text-[10px] font-black text-[#906000]">+</span></div></div></div>
                <div className="mt-3 rounded-2xl border border-[#c9d9cc] bg-white p-3"><div className="flex items-center justify-between"><p className="text-xs font-black">HARI INI</p><p className="text-[10px] font-bold text-[#0f6849]">3 TERPETAKAN</p></div><MapRow dot="bg-[#3d84c6]" label="Revisi desain publikasi" label2="Kuliah"/><MapRow dot="bg-[#0f6849]" label="Rapat divisi acara" label2="Organisasi"/></div>
              </div>
            </div>
            <div className="atlas-note absolute -bottom-1 -left-5 -rotate-[5deg] rounded-xl bg-[#dff3e5] px-4 py-3 text-[#103626] shadow-xl shadow-black/15"><p className="text-[10px] font-black tracking-[.14em]">SMALL WIN</p><p className="mt-1 text-sm font-extrabold">8 hal selesai minggu ini ✦</p></div>
          </div>
        </div>
      </section>

      <div className="atlas-ticker overflow-hidden border-y border-[#d3ddd4] bg-[#f6f8f1] py-4"><div className="flex min-w-max items-center gap-6 text-sm font-black tracking-[.12em] text-[#103626]"><span>RUANG UNTUK KULIAH</span><i className="h-2 w-2 rounded-full bg-[#d9684e]"/><span>RITME UNTUK ORGANISASI</span><i className="h-2 w-2 rounded-full bg-[#0f6849]"/><span>ARAH UNTUK AMBISI</span><i className="h-2 w-2 rounded-full bg-[#d1ae2c]"/><span>RUANG UNTUK KULIAH</span><i className="h-2 w-2 rounded-full bg-[#d9684e]"/><span>RITME UNTUK ORGANISASI</span><i className="h-2 w-2 rounded-full bg-[#0f6849]"/></div></div>

      <section id="atlas" className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:px-12"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-black tracking-[.16em] text-[#0f6849]">THE ATLAS METHOD</p><h2 className="font-display mt-4 text-4xl font-black leading-[.95] tracking-[-.06em] sm:text-5xl">Bukan cuma to-do list.<br/>Ini peta hidup kampusmu.</h2><p className="mt-6 max-w-sm leading-7 text-[#64746a]">Kamu tidak perlu mengingat semuanya. Cukup beri konteks, lalu nGampUS membantu memperlihatkan arah berikutnya.</p><Link href="/register" className="mt-7 inline-flex items-center gap-2 font-extrabold text-[#0f6849]">Bangun peta pertamamu <MoveUpRight size={17}/></Link></div><div className="grid gap-4 sm:grid-cols-2"><AtlasCard number="01" title="Tangkap" text="Catat tugas, reminder, atau ide sebelum hilang dari kepala." icon={<Target size={22}/>} tone="bg-[#e2efff]"/><AtlasCard number="02" title="Hubungkan" text="Tempatkan setiap komitmen di semester, organisasi, atau proker yang tepat." icon={<Layers3 size={22}/>} tone="bg-[#dff3e5]"/><AtlasCard number="03" title="Jalankan" text="Lihat mana yang mendesak, lalu ubah fokus menjadi progres kecil yang nyata." icon={<Clock3 size={22}/>} tone="bg-[#fff0c9]"/><AtlasCard number="04" title="Refleksikan" text="Tutup minggu dengan rekap yang membuat ritmemu terlihat." icon={<Check size={22}/>} tone="bg-[#eee3ff]"/></div></div></section>

      <section className="mx-auto max-w-7xl px-5 pb-24 sm:px-8 lg:px-12"><div className="relative overflow-hidden rounded-[2rem] bg-[#103626] px-6 py-10 text-white sm:px-10 sm:py-14"><div className="absolute -right-28 -top-32 h-80 w-80 rounded-full border-[40px] border-[#c8ef70]/15"/><div className="relative grid gap-10 lg:grid-cols-[.95fr_1.05fr] lg:items-end"><div><p className="text-xs font-black tracking-[.16em] text-[#c8ef70]">YOUR CAMPUS, YOUR SYSTEM</p><h2 className="font-display mt-4 max-w-xl text-4xl font-black leading-[.94] tracking-[-.06em] sm:text-5xl">Kamu punya banyak hal untuk dituju. Jangan jalan tanpa peta.</h2></div><div className="lg:justify-self-end"><p className="max-w-md leading-7 text-[#c5d6ca]">Buat workspace pribadi, mulai dari satu kegiatan, lalu biarkan gambaran besarnya terbentuk pelan-pelan.</p><Link href="/register" className="mt-6 inline-flex items-center gap-3 rounded-2xl bg-[#c8ef70] px-5 py-4 font-extrabold text-[#103626] shadow-[0_7px_0_#82a737] hover:-translate-y-0.5">Mulai sekarang, gratis <ArrowRight size={18}/></Link></div></div></div></section>

      <footer className="border-t border-[#d3ddd4] bg-[#f6f8f1]"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4 px-5 py-8 text-sm text-[#65746a] sm:px-8 lg:px-12"><Link href="/" className="font-display text-xl font-black tracking-[-.06em] text-[#103626]">nGamp<span className="text-[#0f6849]">US</span></Link><span>Personal workspace for campus life.</span><div className="flex gap-4 font-bold"><Link href="/login" className="hover:text-[#0f6849]">Masuk</Link><Link href="/register" className="hover:text-[#0f6849]">Daftar</Link></div></div></footer>
    </main>
  );
}

function MapRow({ dot, label, label2 }: { dot: string; label: string; label2: string }) { return <div className="mt-3 flex items-center gap-3 rounded-xl bg-[#f4f7f3] px-3 py-2"><span className={`h-2.5 w-2.5 rounded-full ${dot}`}/><span className="min-w-0 flex-1 truncate text-sm font-bold">{label}</span><span className="text-[10px] font-bold text-[#718076]">{label2}</span></div>; }
function AtlasCard({ number, title, text, icon, tone }: { number: string; title: string; text: string; icon: React.ReactNode; tone: string }) { return <article className={`${tone} atlas-card relative min-h-56 overflow-hidden rounded-[1.6rem] border border-[#d5dfd6] p-6`}><span className="font-display text-5xl font-black tracking-[-.08em] text-[#103626]/10">{number}</span><div className="absolute bottom-6 left-6 right-6"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white/75 text-[#103626]">{icon}</span><h3 className="font-display mt-4 text-2xl font-black tracking-[-.05em]">{title}</h3><p className="mt-2 max-w-xs text-sm leading-6 text-[#536359]">{text}</p></div></article>; }
