import Link from "next/link";
import { ArrowUpRight, Building2 } from "lucide-react";
import { ConfirmDeleteForm } from "@/components/ui/confirm-delete-form";
import { createClient } from "@/lib/supabase/server";
import { OrganizationForm } from "@/components/organizations/organization-form";
import { deleteOrganization } from "./actions";

export default async function OrganizationsPage() {
  const supabase = await createClient();
  const { data: organizations } = await supabase.from("organizations").select("*").order("created_at", { ascending: false });

  return <div className="mx-auto max-w-5xl px-5 py-8 sm:px-8 lg:px-10"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold text-[var(--brand)]">RUANG KOLABORASI</p><h1 className="font-display mt-1 text-4xl font-extrabold tracking-[-.045em]">Organisasi saya</h1><p className="mt-2 text-[var(--muted)]">Simpan semua ruang tempat kamu tumbuh dan berkontribusi.</p></div><OrganizationForm/></header><section className="mt-8 grid gap-4 sm:grid-cols-2">{organizations?.length ? organizations.map((organization) => <article key={organization.id} className="rounded-2xl border border-[var(--line)] bg-white p-5 transition hover:border-[#b9ddc6] hover:shadow-sm"><div className="flex justify-between gap-4"><div className="grid h-11 w-11 place-items-center rounded-xl bg-[#f4f0e7] text-[#8b7242]"><Building2 size={20}/></div><ConfirmDeleteForm action={deleteOrganization} id={organization.id} itemName={`organisasi “${organization.nama_organisasi}”`}/></div><p className="mt-6 text-xs font-bold uppercase tracking-[.12em] text-[var(--brand)]">{organization.tipe}</p><h2 className="font-display mt-1 text-xl font-extrabold">{organization.nama_organisasi}</h2><p className="mt-3 line-clamp-2 min-h-10 text-sm leading-5 text-[var(--muted)]">{organization.catatan || "Belum ada catatan untuk organisasi ini."}</p><Link href={`/organisasi/${organization.id}`} className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-[var(--brand)] hover:text-[var(--brand-dark)]">Kelola organisasi <ArrowUpRight size={16}/></Link></article>) : <div className="col-span-full rounded-2xl border border-dashed border-[var(--line)] bg-white px-6 py-16 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-xl bg-[#f4f0e7] text-[#8b7242]"><Building2/></div><h2 className="font-display mt-4 text-xl font-extrabold">Ruang kontribusimu masih kosong</h2><p className="mt-2 text-sm text-[var(--muted)]">Tambahkan organisasi, UKM, atau kepanitiaan pertamamu.</p></div>}</section></div>;
}
