import { CalendarDays, CheckCircle2 } from "lucide-react";
import { deleteSemester, setActiveSemester } from "./actions";
import { SemesterForm } from "@/components/semester/semester-form";
import { createClient } from "@/lib/supabase/server";
import { ConfirmDeleteForm } from "@/components/ui/confirm-delete-form";

export default async function SemesterPage() {
  const supabase = await createClient();
  const { data: semesters } = await supabase.from("semesters").select("*").order("tanggal_mulai", { ascending: false });
  return <div className="mx-auto max-w-5xl px-5 py-8 sm:px-8 lg:px-10"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold text-[var(--brand)]">KONTEKS AKADEMIK</p><h1 className="font-display mt-1 text-4xl font-extrabold tracking-[-.045em]">Semester kamu</h1><p className="mt-2 text-[var(--muted)]">Tandai satu semester aktif untuk menjaga dashboard tetap fokus.</p></div><SemesterForm/></header><section className="mt-8 space-y-3">{semesters?.length ? semesters.map((semester) => <article key={semester.id} className={`surface-lift flex flex-wrap items-center gap-4 rounded-2xl border p-5 transition ${semester.is_active ? "border-[var(--brand)] bg-[#f5fbf7] ring-2 ring-[var(--brand)]/10" : "border-[var(--line)] bg-white"}`}><div className={`grid h-12 w-12 place-items-center rounded-2xl ${semester.is_active ? "bg-[var(--brand)] text-white shadow-md shadow-[#0f6849]/20" : "bg-[#f4f0e7] text-[#8b7242]"}`}><CalendarDays size={22}/></div><div className="min-w-[180px] flex-1"><div className="flex items-center gap-2.5"><h2 className="font-display text-xl font-extrabold">{semester.nama_semester}</h2>{semester.is_active ? <span className="inline-flex items-center gap-1 rounded-full bg-[var(--brand-soft)] px-2.5 py-0.5 text-xs font-black text-[var(--brand-dark)]">● Aktif</span> : <span className="rounded-full bg-[#f7f8f5] px-2.5 py-0.5 text-xs font-bold text-[var(--muted)]">Arsip</span>}</div><p className="mt-1 text-sm text-[var(--muted)]">{new Intl.DateTimeFormat("id-ID", { dateStyle: "medium" }).format(new Date(`${semester.tanggal_mulai}T00:00:00`))} — {new Intl.DateTimeFormat("id-ID", { dateStyle: "medium" }).format(new Date(`${semester.tanggal_selesai}T00:00:00`))}</p></div><div className="ml-auto flex flex-wrap items-center gap-2">{!semester.is_active && <form action={setActiveSemester}><input type="hidden" name="id" value={semester.id}/><button className="inline-flex items-center gap-1.5 rounded-xl bg-white px-3.5 py-2 text-xs font-bold text-[var(--ink)] ring-1 ring-[var(--line)] transition hover:bg-[var(--brand-soft)] hover:text-[var(--brand-dark)] hover:ring-[var(--brand)]/30"><CheckCircle2 size={15}/> Jadikan aktif</button></form>}<SemesterForm semester={semester}/><ConfirmDeleteForm action={deleteSemester} id={semester.id} itemName={`semester “${semester.nama_semester}”`}/></div></article>) : <div className="rounded-2xl border border-dashed border-[var(--line)] bg-white px-6 py-16 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-xl bg-[#dcefe4] text-[var(--brand)]"><CalendarDays/></div><h2 className="font-display mt-4 text-xl font-extrabold">Mulai dari satu semester</h2><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-[var(--muted)]">Buat semester pertamamu agar aktivitas memiliki konteks yang jelas.</p></div>}</section></div>;
}
